name: 🚀 SAP Strategic AI Platform CI/CD

on:
  push:
    branches: [ develop, staging, main ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:  # 手動実行を許可

env:
  NODE_VERSION: '18'
  AWS_REGION: 'us-east-1'

jobs:
  # 1. コード品質チェック
  quality-check:
    name: 🔍 Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Tests
        run: npm test

      - name: 📊 Lint Check
        run: npm run lint || echo "⚠️ Lint warnings found but continuing..."

      - name: 🏗️ Build Check
        run: npm run build

  # 2. CDK Diff Check（開発・ステージング用）
  cdk-diff:
    name: 📋 CDK Infrastructure Diff
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: quality-check
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 📦 Install CDK Dependencies
        run: |
          cd cdk
          npm ci

      - name: 🔍 CDK Diff
        run: |
          cd cdk
          npx cdk diff

  # 3. デプロイ（ブランチ別）
  deploy:
    name: 🚀 Deploy to AWS
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'development' }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # フロントエンドビルド
      - name: 📦 Install Frontend Dependencies
        run: npm ci

      - name: 🏗️ Build Frontend
        run: npm run build

      # CDKデプロイ
      - name: 📦 Install CDK Dependencies
        run: |
          cd cdk
          npm ci

      - name: 🚀 Deploy CDK Infrastructure
        run: |
          cd cdk
          npx cdk deploy --require-approval never

      # Amplifyデプロイ（本番・ステージングのみ）
      - name: 🌐 Deploy to Amplify
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          # Amplifyアプリの自動デプロイ（GitHubプッシュでトリガー）
          echo "✅ Amplify auto-deploy triggered by GitHub push"

  # 4. 通知
  notify:
    name: 📢 Deployment Notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: 📊 Deployment Status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "✅ デプロイメント成功: ${{ github.ref }}"
          else
            echo "❌ デプロイメント失敗: ${{ github.ref }}"
          fi